apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: i-love-cloud-namespace
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      
      access_log /var/log/nginx/access.log main;
      error_log /var/log/nginx/error.log debug;
      
      server {
        listen 80;
        
        location /stocks {
          proxy_pass http://stock-service:5001;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Connection "";
          proxy_read_timeout 90s;
          proxy_send_timeout 90s;
        }

        location /capital-gains {
          proxy_pass http://capital-gains:5003;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Connection "";
          proxy_read_timeout 90s;
          proxy_send_timeout 90s;
        }
      }
    }