services:
  stocks1-a:
    build:
      context: ./stocks1
    container_name: stocks1-a
    ports:
      - "5001:8000"
    expose:
      - "8000"
    depends_on:
      - db
    restart: always
    environment:
      - MONGO_URI=mongodb://db:27017/stocks_db

  stocks1-b:
    build:
      context: ./stocks1
    container_name: stocks1-b
    ports:
      - "5004:8000"
    expose:
      - "8000"
    depends_on:
      - db
    restart: always
    environment:
      - MONGO_URI=mongodb://db:27017/stocks_db


  stocks2:
    build:
      context: ./stocks2
    ports:
      - "5002:8000"
    expose:
      - "8000"
    depends_on:
      - db
    restart: always
    environment:
      - MONGO_URI=mongodb://db:27017/stocks_db

  capital-gains:
    build:
      context: ./capital_gains_service
    ports:
      - "5003:8080"
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2
    restart: always

  db:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always
    volumes:
      - db_data:/data/db

  nginx:
    image: nginx:latest
    container_name: ex2-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2
      - capital-gains
    restart: always


volumes:
  db_data:



