apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  namespace: i-love-cloud-namespace
  labels:
    app: stock-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
      - name: stock-service
        image: stock-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://db:27017/stocks_db"
