apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: i-love-cloud-namespace
spec:
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
