apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: i-love-cloud-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/mongo
